### ISSUE TITLE
deploy skeleton for intro and int-adv course

### ISSUE THREAD

**Issue by richpauloo** [ryanpeek/r4wrds#39]
Here is a minimal example that we use to build on: https://richpauloo.github.io/delete/

GH repo for the min example is here: https://github.com/richpauloo/delete/

The idea is to use 3 distill projects. The first is a splash page that sits in the root dir, which contains two subdirectories for the intro and int_adv courses. The subdirectories are entirely self-contained in that they have their own images, data, RProj file, css - even if there's lots of duplication. The self-containment is nice because when we're writing lessons and use here(), we don't need to write here("intro", "data", ...), but rather can write here("data", ...) and that's what we want course participants to view. 

In the intro and adv courses, I added a home icon in the right navbar that directs back to the root dir. Also, each module's output_dir (in site.yml) is "." (no more "docs") so that the final urls for each module will take the form: r4wrds.com/{intro or int-adv}/{m_module_name.html}.

Down the line we can format links to intro and adv courses on in the root dir so they're more appealing. This is just to set the skeleton so we can develop and have our deploy skeleton already set up.

Let me know what you think, and if it's good to go I'll refactor! Then we can rename this directory "r4wrds". 

A related issue I've been thinking of that we can discuss... maybe we can call the int-adv class just "intermediate", and leave room for us to develop an advanced course sometime in the future that brings in the more advanced concepts we thought were out of scope of the int-adv course (e.g., package building).

**Comment by ryanpeek** [comment]
Nice! I checked it out, and this all seems great. Let's go ahead move forward with the approach you outlined above. Do you want me to rename this repo to **r4wrds**? 

And I agree simplifying the course to "intermediate" makes sense, and that's really the level we are focusing on. I also like the idea that we keep this as simple and straight forward as possible, it will be easier to teach and maintain that way, and I don't want to overpromise stuff that while it would be great to have/do, it's out of the scope of what we are allotted currently.

Let me know how you want to proceed and I can review/setup a PR/rename as needed. Thanks for seeing how this works...I think this will be cool! One quick organization/branch question...will we have a branch named **`intro`** and a branch **`intermediate`** which will be like the *main* branches for each Rproj, and then we can pull develop into those and then pull just the pieces we need into the main deployed branch? Or do we want to have a specific deployed branch we'd use for this, and the main branch is more like the final clean version we can package/version?  Let's chat more and maybe sketch this out so I can visualize what we've got going on. :)

**Comment by richpauloo** [comment]
Hey Ryan, thanks! If you rename the repo of r4wrds, I can set up the structure that we have in the minimal example. 

Since you agree, let's also just call the second course "intermediate", and leave open the possibility of an advanced course down the line. This structure also allows us any number of courses (e.g., "Shiny for water resources", "stats for water resources", etc...).

What you described in terms of branching is also what I envisioned. We deploy from "main" for the final product, (and we can deploy "develop" during development if we want to test drive the final product before moving it to "main"). We treat the develop branch as the place where lots of changes can happen. We have two branches coming off of "develop" called "develop-intro" and "develop-intermediate" that we can branch to develop modules, then merge those modules back into "develop-intro" and "develop-intermediate". You may ask, "why have a 'develop' branch?" The main reason I see is that it serves as a "pre-production" branch that we can use to merge all develop subbranches into and test drive the final product before merging into the main branch and calling it done.

If you agree, here's a task list we can check off:

- [ ] Ryan renames repo to r4wrds 
- [ ] Rich refactors repo according to conversation
- [ ] Rich creates two branches from develop called "develop-intro" and "develop-intermediate" that we can start branching off of.

Let me know if you agree, and feel free to edit this post and task list!

![image](https://user-images.githubusercontent.com/10336683/114412412-ed483f00-9b61-11eb-8f42-c057a2aa82e4.png)

**Comment by ryanpeek** [comment]
Sounds good...I've just renamed the repo **`r4wrds`**. Your list looks good, but just want to check, are you going to put each of the courses (intro and intermediate) into a new folder? I'm adding that to a list as well. Everything else makes sense, look forward to seeing it all!

**Comment by richpauloo** [comment]
Awesome thanks! 

And yes, each "subpage" to the main page r4wrds.com will have its own folder, and the entire site for that course will be contained in that folder. So we'll have an intro folder, and int (for intermediate) folder, and in the future, any other folder we want! Like "adv", "shiny" and so on.
