### ISSUE TITLE
tag for Github issue (or PR? - e.g., "edit this page") on distill pages

### ISSUE THREAD

**Issue by richpauloo** [ryanpeek/r4wrds#60]

**Comment by ryanpeek** [comment]
I think this just requires adding: `citation_url: https://rstudio.github.io/distill` in the index.Rmd for the site and each course page.

See the [distill GitHub site for more details](https://github.com/rstudio/distill/tree/master/docs)

**Comment by ryanpeek** [comment]
@richpauloo: I think I've addressed this issue with #69 , let me know if you are good with this and we can close this one too.
