### ISSUE TITLE
leaflet not rendering in intermediate/m_interactive_viz.Rmd

### ISSUE THREAD

**Issue by richpauloo** [ryanpeek/r4wrds#65]
Might be related to package versions. Try updating all packages prior to knit.

Might also be related to use of `icons`.

Otherwise, it's a teachable moment. =)

**Comment by ryanpeek** [comment]
I find it renders, but the layer doesn't show up by default. You have to click on/off and then it appears. Unclear why this is. Agree...can try using standard markers instead to see if this solves the problem.

**Comment by richpauloo** [comment]
Bugs present in `icons()` and `addMarkers()` that I didn't troubleshoot in the interest of time. 

`addCircleMarkers()` was error free, so I went with that.
